language: ruby
rvm:
  - 2.0.0
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate spec
before_script:
  - psql -c 'create database chief_test' -U postgres
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq imagemagick