development: &default
  adapter: postgresql
  database: chief_development
  encoding: unicode
  min_messages: warning
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: chief_test